name: Manual Workflow Example 123

on:
  workflow_dispatch:

jobs:
  log-user:
    runs-on: ubuntu-latest
    steps:
      - name: Print actor (user who triggered this workflow in uppercase)
        run: |
          actor=$(echo "${{ github.actor }}" | tr '[:lower:]' '[:upper:]')
          echo "Usuario en mayúsculas: $actor_mayusculas"
