name: Manual Workflow Example 123

on:
  workflow_dispatch:

jobs:
  log-user:
    runs-on: ubuntu-latest
    steps:
      - name: Print actor (user who triggered this workflow in uppercase)
        run: |
          # Guardar el actor en una variable
          actor="${{ github.actor }}"
          # Convertir a mayúsculas usando bash
          actor_mayusculas=$(echo "$actor" | tr '[:lower:]' '[:upper:]')
          # Mostrar ambos valores
          echo "Usuario original: $actor"
          echo "Usuario en mayúsculas: $actor_mayusculas"
