name: Manual Workflow Example

on:
  workflow_dispatch:

jobs:
  log-user:
    runs-on: ubuntu-latest
    steps:
      - name: Print actor (user who triggered this workflow)
        run: echo "${{ github.actor }}"
